### ISSUE TITLE
Conflict between multiple versions of ZalgoPromise

### ISSUE THREAD

**Issue by delego-wlritchi** [krakenjs/zalgo-promise#1]
Use case: Alice has implemented a web store and has used ZalgoPromise on her website, through another library (e.g. post-robot). She wants to add PayPal integration using the PayPal SDK, which bundles a different (and frequently-updated) version of ZalgoPromise.

ZalgoPromise uses a property on the global object. If two versions of ZalgoPromise are loaded, they will attempt to share this property. Until recently, this has turned out okay, but with version 1.0.24, error dispatching now uses new fields on this property. If a version before 1.0.24 is loaded first, and initializes the property without these fields, the newer version of ZalgoPromise on that page can fail.

I'd like to be able to say that the correct solution here is to not mix-and-match versions, but I think the use case above is both compelling and likely to happen many times over. In my opinion, it would be better to make it possible to load multiple versions of ZalgoPromise without risking them conflicting. This might be accomplished by using a global property name that includes the version of the library, or by storing state in a closure rather than on the global object.

**Comment by bluepnume** [comment]
Yeah, agreed. We should probably version this global based on the major version of the library. Within major versions we should not break backwards compatibility.

**Comment by mnicpt** [comment]
This looks to have been fixed.
